services:
  java_db:
    container_name: java_db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: deneme
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d deneme"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: todo_app
    depends_on:
      java_db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: todoapp
      SPRING_DATASOURCE_URL: jdbc:postgresql://java_db:5432/deneme
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

volumes:
  pgdata: {}
